#!/bin/sh

CONFIG_FILE_DIR="/usr/share/nginx/html/src"
CONFIG_FILE_PATH="${CONFIG_FILE_DIR}/config.js"

mkdir -p "$CONFIG_FILE_DIR"

cat > "$CONFIG_FILE_PATH" <<EOF
window.configs = {
  "VUE_APP_OIDC_PROVIDER_URL": "${VUE_APP_OIDC_PROVIDER_URL}",
  "VUE_APP_OIDC_CLIENT_SECRET": "${VUE_APP_OIDC_CLIENT_SECRET}",
  "VUE_APP_OIDC_CLIENT_ID": "${VUE_APP_OIDC_CLIENT_ID}",
  "VUE_APP_MANAGEMENT_API_URI": "${VUE_APP_MANAGEMENT_API_URI}",
};
EOF

exec "$@"
