apiVersion: v1
kind: Service
metadata:
  name: subscriber-mock
spec:
  selector:
    app: subscriber-mock
  ports:
    - protocol: "TCP"
      port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-mock
spec:
  selector:
    matchLabels:
      app: subscriber-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriber-mock
    spec:
      containers:
        - name: subscriber-mock
          image: k3d-im-bb-registry.localhost:5000/subscriber-mock:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
