apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher
  name: ranchernp
  namespace: cattle-system
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https-internal
      nodePort: 30081
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: rancher
  type: NodePort
