apiVersion: v1
kind: Service
metadata:
  name: management-api
spec:
  selector:
    app: management-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api
spec:
  selector:
    matchLabels:
      app: management-api
  replicas: 1
  template:
    metadata:
      labels:
        app: management-api
    spec:
      containers:
        - name: management-api
          image: k3d-im-bb-registry.localhost:5000/management-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
