apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - job.yaml
  - secret.yaml

images:
  - name: image
    newName: k3d-im-bb-registry.localhost:5000/schema
    newTag: latest
