/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * access right given for a specific subject (ServiceClient) for specific service (service_code) owned by some client. This object does not represent endpoint-level access rights
 */
@JsonPropertyOrder({
  AccessRight.JSON_PROPERTY_SERVICE_CODE,
  AccessRight.JSON_PROPERTY_SERVICE_TITLE,
  AccessRight.JSON_PROPERTY_RIGHTS_GIVEN_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AccessRight {
  public static final String JSON_PROPERTY_SERVICE_CODE = "service_code";
  private String serviceCode;

  public static final String JSON_PROPERTY_SERVICE_TITLE = "service_title";
  private String serviceTitle;

  public static final String JSON_PROPERTY_RIGHTS_GIVEN_AT = "rights_given_at";
  private OffsetDateTime rightsGivenAt;

  public AccessRight() {
  }

  @JsonCreator
  public AccessRight(
    @JsonProperty(JSON_PROPERTY_SERVICE_TITLE) String serviceTitle, 
    @JsonProperty(JSON_PROPERTY_RIGHTS_GIVEN_AT) OffsetDateTime rightsGivenAt
  ) {
    this();
    this.serviceTitle = serviceTitle;
    this.rightsGivenAt = rightsGivenAt;
  }

  public AccessRight serviceCode(String serviceCode) {
    
    this.serviceCode = serviceCode;
    return this;
  }

   /**
   * service code
   * @return serviceCode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServiceCode() {
    return serviceCode;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }


   /**
   * service title
   * @return serviceTitle
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceTitle() {
    return serviceTitle;
  }




   /**
   * access right given at
   * @return rightsGivenAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RIGHTS_GIVEN_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRightsGivenAt() {
    return rightsGivenAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessRight accessRight = (AccessRight) o;
    return Objects.equals(this.serviceCode, accessRight.serviceCode) &&
        Objects.equals(this.serviceTitle, accessRight.serviceTitle) &&
        Objects.equals(this.rightsGivenAt, accessRight.rightsGivenAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceCode, serviceTitle, rightsGivenAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessRight {\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("    serviceTitle: ").append(toIndentedString(serviceTitle)).append("\n");
    sb.append("    rightsGivenAt: ").append(toIndentedString(rightsGivenAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

