/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.Backup;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * security server backup with extra information
 */
@JsonPropertyOrder({
  BackupExt.JSON_PROPERTY_BACKUP,
  BackupExt.JSON_PROPERTY_LOCAL_CONF_PRESENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BackupExt {
  public static final String JSON_PROPERTY_BACKUP = "backup";
  private Backup backup;

  public static final String JSON_PROPERTY_LOCAL_CONF_PRESENT = "local_conf_present";
  private Boolean localConfPresent;

  public BackupExt() {
  }

  public BackupExt backup(Backup backup) {
    
    this.backup = backup;
    return this;
  }

   /**
   * Get backup
   * @return backup
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BACKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Backup getBackup() {
    return backup;
  }


  @JsonProperty(JSON_PROPERTY_BACKUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBackup(Backup backup) {
    this.backup = backup;
  }


  public BackupExt localConfPresent(Boolean localConfPresent) {
    
    this.localConfPresent = localConfPresent;
    return this;
  }

   /**
   * Get localConfPresent
   * @return localConfPresent
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCAL_CONF_PRESENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLocalConfPresent() {
    return localConfPresent;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_CONF_PRESENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocalConfPresent(Boolean localConfPresent) {
    this.localConfPresent = localConfPresent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupExt backupExt = (BackupExt) o;
    return Objects.equals(this.backup, backupExt.backup) &&
        Objects.equals(this.localConfPresent, backupExt.localConfPresent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backup, localConfPresent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupExt {\n");
    sb.append("    backup: ").append(toIndentedString(backup)).append("\n");
    sb.append("    localConfPresent: ").append(toIndentedString(localConfPresent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

