/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * backup encryption statuses
 */
@JsonPropertyOrder({
  BackupEncryptionStatus.JSON_PROPERTY_BACKUP_ENCRYPTION_STATUS,
  BackupEncryptionStatus.JSON_PROPERTY_BACKUP_ENCRYPTION_KEYS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BackupEncryptionStatus {
  public static final String JSON_PROPERTY_BACKUP_ENCRYPTION_STATUS = "backup_encryption_status";
  private Boolean backupEncryptionStatus;

  public static final String JSON_PROPERTY_BACKUP_ENCRYPTION_KEYS = "backup_encryption_keys";
  private List<String> backupEncryptionKeys;

  public BackupEncryptionStatus() {
  }

  @JsonCreator
  public BackupEncryptionStatus(
    @JsonProperty(JSON_PROPERTY_BACKUP_ENCRYPTION_STATUS) Boolean backupEncryptionStatus
  ) {
    this();
    this.backupEncryptionStatus = backupEncryptionStatus;
  }

   /**
   * Get backupEncryptionStatus
   * @return backupEncryptionStatus
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BACKUP_ENCRYPTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getBackupEncryptionStatus() {
    return backupEncryptionStatus;
  }




  public BackupEncryptionStatus backupEncryptionKeys(List<String> backupEncryptionKeys) {
    
    this.backupEncryptionKeys = backupEncryptionKeys;
    return this;
  }

  public BackupEncryptionStatus addBackupEncryptionKeysItem(String backupEncryptionKeysItem) {
    if (this.backupEncryptionKeys == null) {
      this.backupEncryptionKeys = new ArrayList<>();
    }
    this.backupEncryptionKeys.add(backupEncryptionKeysItem);
    return this;
  }

   /**
   * Get backupEncryptionKeys
   * @return backupEncryptionKeys
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BACKUP_ENCRYPTION_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getBackupEncryptionKeys() {
    return backupEncryptionKeys;
  }


  @JsonProperty(JSON_PROPERTY_BACKUP_ENCRYPTION_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackupEncryptionKeys(List<String> backupEncryptionKeys) {
    this.backupEncryptionKeys = backupEncryptionKeys;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupEncryptionStatus backupEncryptionStatus = (BackupEncryptionStatus) o;
    return Objects.equals(this.backupEncryptionStatus, backupEncryptionStatus.backupEncryptionStatus) &&
        Objects.equals(this.backupEncryptionKeys, backupEncryptionStatus.backupEncryptionKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupEncryptionStatus, backupEncryptionKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupEncryptionStatus {\n");
    sb.append("    backupEncryptionStatus: ").append(toIndentedString(backupEncryptionStatus)).append("\n");
    sb.append("    backupEncryptionKeys: ").append(toIndentedString(backupEncryptionKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

