/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.Client;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Request to add client. Carries a Client and ignore warnings parameter
 */
@JsonPropertyOrder({
  ClientAdd.JSON_PROPERTY_CLIENT,
  ClientAdd.JSON_PROPERTY_IGNORE_WARNINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ClientAdd {
  public static final String JSON_PROPERTY_CLIENT = "client";
  private Client client;

  public static final String JSON_PROPERTY_IGNORE_WARNINGS = "ignore_warnings";
  private Boolean ignoreWarnings = false;

  public ClientAdd() {
  }

  public ClientAdd client(Client client) {
    
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Client getClient() {
    return client;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClient(Client client) {
    this.client = client;
  }


  public ClientAdd ignoreWarnings(Boolean ignoreWarnings) {
    
    this.ignoreWarnings = ignoreWarnings;
    return this;
  }

   /**
   * if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail
   * @return ignoreWarnings
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IGNORE_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIgnoreWarnings() {
    return ignoreWarnings;
  }


  @JsonProperty(JSON_PROPERTY_IGNORE_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnoreWarnings(Boolean ignoreWarnings) {
    this.ignoreWarnings = ignoreWarnings;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientAdd clientAdd = (ClientAdd) o;
    return Objects.equals(this.client, clientAdd.client) &&
        Objects.equals(this.ignoreWarnings, clientAdd.ignoreWarnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(client, ignoreWarnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientAdd {\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    ignoreWarnings: ").append(toIndentedString(ignoreWarnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

