/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.CsrGenerate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * KeyLabelWithCsrGenerate
 */
@JsonPropertyOrder({
  KeyLabelWithCsrGenerate.JSON_PROPERTY_KEY_LABEL,
  KeyLabelWithCsrGenerate.JSON_PROPERTY_CSR_GENERATE_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class KeyLabelWithCsrGenerate {
  public static final String JSON_PROPERTY_KEY_LABEL = "key_label";
  private String keyLabel;

  public static final String JSON_PROPERTY_CSR_GENERATE_REQUEST = "csr_generate_request";
  private CsrGenerate csrGenerateRequest;

  public KeyLabelWithCsrGenerate() {
  }

  public KeyLabelWithCsrGenerate keyLabel(String keyLabel) {
    
    this.keyLabel = keyLabel;
    return this;
  }

   /**
   * label for the new key
   * @return keyLabel
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKeyLabel() {
    return keyLabel;
  }


  @JsonProperty(JSON_PROPERTY_KEY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyLabel(String keyLabel) {
    this.keyLabel = keyLabel;
  }


  public KeyLabelWithCsrGenerate csrGenerateRequest(CsrGenerate csrGenerateRequest) {
    
    this.csrGenerateRequest = csrGenerateRequest;
    return this;
  }

   /**
   * Get csrGenerateRequest
   * @return csrGenerateRequest
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CSR_GENERATE_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CsrGenerate getCsrGenerateRequest() {
    return csrGenerateRequest;
  }


  @JsonProperty(JSON_PROPERTY_CSR_GENERATE_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCsrGenerateRequest(CsrGenerate csrGenerateRequest) {
    this.csrGenerateRequest = csrGenerateRequest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyLabelWithCsrGenerate keyLabelWithCsrGenerate = (KeyLabelWithCsrGenerate) o;
    return Objects.equals(this.keyLabel, keyLabelWithCsrGenerate.keyLabel) &&
        Objects.equals(this.csrGenerateRequest, keyLabelWithCsrGenerate.csrGenerateRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyLabel, csrGenerateRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyLabelWithCsrGenerate {\n");
    sb.append("    keyLabel: ").append(toIndentedString(keyLabel)).append("\n");
    sb.append("    csrGenerateRequest: ").append(toIndentedString(csrGenerateRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

