/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * certificate key usage
 */
public enum KeyUsage {
  
  DIGITAL_SIGNATURE("DIGITAL_SIGNATURE"),
  
  NON_REPUDIATION("NON_REPUDIATION"),
  
  KEY_ENCIPHERMENT("KEY_ENCIPHERMENT"),
  
  DATA_ENCIPHERMENT("DATA_ENCIPHERMENT"),
  
  KEY_AGREEMENT("KEY_AGREEMENT"),
  
  KEY_CERT_SIGN("KEY_CERT_SIGN"),
  
  CRL_SIGN("CRL_SIGN"),
  
  ENCIPHER_ONLY("ENCIPHER_ONLY"),
  
  DECIPHER_ONLY("DECIPHER_ONLY");

  private String value;

  KeyUsage(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static KeyUsage fromValue(String value) {
    for (KeyUsage b : KeyUsage.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

