/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.OcspResponder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Ocsp responder diagnostics
 */
@JsonPropertyOrder({
  OcspResponderDiagnostics.JSON_PROPERTY_DISTINGUISHED_NAME,
  OcspResponderDiagnostics.JSON_PROPERTY_OCSP_RESPONDERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OcspResponderDiagnostics {
  public static final String JSON_PROPERTY_DISTINGUISHED_NAME = "distinguished_name";
  private String distinguishedName;

  public static final String JSON_PROPERTY_OCSP_RESPONDERS = "ocsp_responders";
  private List<OcspResponder> ocspResponders = new ArrayList<>();

  public OcspResponderDiagnostics() {
  }

  @JsonCreator
  public OcspResponderDiagnostics(
    @JsonProperty(JSON_PROPERTY_DISTINGUISHED_NAME) String distinguishedName, 
    @JsonProperty(JSON_PROPERTY_OCSP_RESPONDERS) List<OcspResponder> ocspResponders
  ) {
    this();
    this.distinguishedName = distinguishedName;
    this.ocspResponders = ocspResponders;
  }

   /**
   * CA distinguished name
   * @return distinguishedName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISTINGUISHED_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDistinguishedName() {
    return distinguishedName;
  }




   /**
   * Get ocspResponders
   * @return ocspResponders
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OCSP_RESPONDERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OcspResponder> getOcspResponders() {
    return ocspResponders;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OcspResponderDiagnostics ocspResponderDiagnostics = (OcspResponderDiagnostics) o;
    return Objects.equals(this.distinguishedName, ocspResponderDiagnostics.distinguishedName) &&
        Objects.equals(this.ocspResponders, ocspResponderDiagnostics.ocspResponders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distinguishedName, ocspResponders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OcspResponderDiagnostics {\n");
    sb.append("    distinguishedName: ").append(toIndentedString(distinguishedName)).append("\n");
    sb.append("    ocspResponders: ").append(toIndentedString(ocspResponders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

