/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OrphanInformation
 */
@JsonPropertyOrder({
  OrphanInformation.JSON_PROPERTY_ORPHANS_EXIST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrphanInformation {
  public static final String JSON_PROPERTY_ORPHANS_EXIST = "orphans_exist";
  private Boolean orphansExist = false;

  public OrphanInformation() {
  }

  public OrphanInformation orphansExist(Boolean orphansExist) {
    
    this.orphansExist = orphansExist;
    return this;
  }

   /**
   * Get orphansExist
   * @return orphansExist
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORPHANS_EXIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOrphansExist() {
    return orphansExist;
  }


  @JsonProperty(JSON_PROPERTY_ORPHANS_EXIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrphansExist(Boolean orphansExist) {
    this.orphansExist = orphansExist;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrphanInformation orphanInformation = (OrphanInformation) o;
    return Objects.equals(this.orphansExist, orphanInformation.orphansExist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orphansExist);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrphanInformation {\n");
    sb.append("    orphansExist: ").append(toIndentedString(orphansExist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

