/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * an action to change state or edit token, key, cert or csr
 */
public enum PossibleAction {
  
  DELETE("DELETE"),
  
  ACTIVATE("ACTIVATE"),
  
  DISABLE("DISABLE"),
  
  LOGIN("LOGIN"),
  
  LOGOUT("LOGOUT"),
  
  REGISTER("REGISTER"),
  
  UNREGISTER("UNREGISTER"),
  
  IMPORT_FROM_TOKEN("IMPORT_FROM_TOKEN"),
  
  GENERATE_KEY("GENERATE_KEY"),
  
  EDIT_FRIENDLY_NAME("EDIT_FRIENDLY_NAME"),
  
  GENERATE_AUTH_CSR("GENERATE_AUTH_CSR"),
  
  GENERATE_SIGN_CSR("GENERATE_SIGN_CSR"),
  
  TOKEN_CHANGE_PIN("TOKEN_CHANGE_PIN");

  private String value;

  PossibleAction(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PossibleAction fromValue(String value) {
    for (PossibleAction b : PossibleAction.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

