/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * security server information
 */
@JsonPropertyOrder({
  SecurityServer.JSON_PROPERTY_ID,
  SecurityServer.JSON_PROPERTY_INSTANCE_ID,
  SecurityServer.JSON_PROPERTY_MEMBER_CLASS,
  SecurityServer.JSON_PROPERTY_MEMBER_CODE,
  SecurityServer.JSON_PROPERTY_SERVER_CODE,
  SecurityServer.JSON_PROPERTY_SERVER_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SecurityServer {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_INSTANCE_ID = "instance_id";
  private String instanceId;

  public static final String JSON_PROPERTY_MEMBER_CLASS = "member_class";
  private String memberClass;

  public static final String JSON_PROPERTY_MEMBER_CODE = "member_code";
  private String memberCode;

  public static final String JSON_PROPERTY_SERVER_CODE = "server_code";
  private String serverCode;

  public static final String JSON_PROPERTY_SERVER_ADDRESS = "server_address";
  private String serverAddress;

  public SecurityServer() {
  }

  public SecurityServer id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * &lt;instance_id&gt;:&lt;member_class&gt;:&lt;member_code&gt;:&lt;security_server_code&gt;
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public SecurityServer instanceId(String instanceId) {
    
    this.instanceId = instanceId;
    return this;
  }

   /**
   * xroad instance id
   * @return instanceId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceId() {
    return instanceId;
  }


  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  public SecurityServer memberClass(String memberClass) {
    
    this.memberClass = memberClass;
    return this;
  }

   /**
   * member class
   * @return memberClass
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEMBER_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemberClass() {
    return memberClass;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberClass(String memberClass) {
    this.memberClass = memberClass;
  }


  public SecurityServer memberCode(String memberCode) {
    
    this.memberCode = memberCode;
    return this;
  }

   /**
   * member code
   * @return memberCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEMBER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemberCode() {
    return memberCode;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberCode(String memberCode) {
    this.memberCode = memberCode;
  }


  public SecurityServer serverCode(String serverCode) {
    
    this.serverCode = serverCode;
    return this;
  }

   /**
   * security server code
   * @return serverCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServerCode() {
    return serverCode;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerCode(String serverCode) {
    this.serverCode = serverCode;
  }


  public SecurityServer serverAddress(String serverAddress) {
    
    this.serverAddress = serverAddress;
    return this;
  }

   /**
   * security server address (ip or name)
   * @return serverAddress
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServerAddress() {
    return serverAddress;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerAddress(String serverAddress) {
    this.serverAddress = serverAddress;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityServer securityServer = (SecurityServer) o;
    return Objects.equals(this.id, securityServer.id) &&
        Objects.equals(this.instanceId, securityServer.instanceId) &&
        Objects.equals(this.memberClass, securityServer.memberClass) &&
        Objects.equals(this.memberCode, securityServer.memberCode) &&
        Objects.equals(this.serverCode, securityServer.serverCode) &&
        Objects.equals(this.serverAddress, securityServer.serverAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, instanceId, memberClass, memberCode, serverCode, serverAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityServer {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    memberClass: ").append(toIndentedString(memberClass)).append("\n");
    sb.append("    memberCode: ").append(toIndentedString(memberCode)).append("\n");
    sb.append("    serverCode: ").append(toIndentedString(serverCode)).append("\n");
    sb.append("    serverAddress: ").append(toIndentedString(serverAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

