/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.Endpoint;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * service for the service description
 */
@JsonPropertyOrder({
  Service.JSON_PROPERTY_ID,
  Service.JSON_PROPERTY_FULL_SERVICE_CODE,
  Service.JSON_PROPERTY_SERVICE_CODE,
  Service.JSON_PROPERTY_TIMEOUT,
  Service.JSON_PROPERTY_TITLE,
  Service.JSON_PROPERTY_SSL_AUTH,
  Service.JSON_PROPERTY_SUBJECTS_COUNT,
  Service.JSON_PROPERTY_URL,
  Service.JSON_PROPERTY_ENDPOINTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Service {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_FULL_SERVICE_CODE = "full_service_code";
  private String fullServiceCode;

  public static final String JSON_PROPERTY_SERVICE_CODE = "service_code";
  private String serviceCode;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  private Integer timeout;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_SSL_AUTH = "ssl_auth";
  private Boolean sslAuth;

  public static final String JSON_PROPERTY_SUBJECTS_COUNT = "subjects_count";
  private Integer subjectsCount;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_ENDPOINTS = "endpoints";
  private List<Endpoint> endpoints;

  public Service() {
  }

  @JsonCreator
  public Service(
    @JsonProperty(JSON_PROPERTY_TITLE) String title
  ) {
    this();
    this.title = title;
  }

  public Service id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * encoded service id, including client id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Service fullServiceCode(String fullServiceCode) {
    
    this.fullServiceCode = fullServiceCode;
    return this;
  }

   /**
   * encoded service code and version
   * @return fullServiceCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullServiceCode() {
    return fullServiceCode;
  }


  @JsonProperty(JSON_PROPERTY_FULL_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullServiceCode(String fullServiceCode) {
    this.fullServiceCode = fullServiceCode;
  }


  public Service serviceCode(String serviceCode) {
    
    this.serviceCode = serviceCode;
    return this;
  }

   /**
   * encoded service code
   * @return serviceCode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServiceCode() {
    return serviceCode;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }


  public Service timeout(Integer timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * service time out value
   * minimum: 0
   * maximum: 1000
   * @return timeout
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTimeout() {
    return timeout;
  }


  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }


   /**
   * service title
   * @return title
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }




  public Service sslAuth(Boolean sslAuth) {
    
    this.sslAuth = sslAuth;
    return this;
  }

   /**
   * service ssl auth
   * @return sslAuth
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SSL_AUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSslAuth() {
    return sslAuth;
  }


  @JsonProperty(JSON_PROPERTY_SSL_AUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSslAuth(Boolean sslAuth) {
    this.sslAuth = sslAuth;
  }


  public Service subjectsCount(Integer subjectsCount) {
    
    this.subjectsCount = subjectsCount;
    return this;
  }

   /**
   * count of acl subjects
   * minimum: 0
   * maximum: 100000
   * @return subjectsCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBJECTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSubjectsCount() {
    return subjectsCount;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectsCount(Integer subjectsCount) {
    this.subjectsCount = subjectsCount;
  }


  public Service url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * service url
   * @return url
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }


  public Service endpoints(List<Endpoint> endpoints) {
    
    this.endpoints = endpoints;
    return this;
  }

  public Service addEndpointsItem(Endpoint endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

   /**
   * list of endpoints linked to this service
   * @return endpoints
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Endpoint> getEndpoints() {
    return endpoints;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoints(List<Endpoint> endpoints) {
    this.endpoints = endpoints;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.id, service.id) &&
        Objects.equals(this.fullServiceCode, service.fullServiceCode) &&
        Objects.equals(this.serviceCode, service.serviceCode) &&
        Objects.equals(this.timeout, service.timeout) &&
        Objects.equals(this.title, service.title) &&
        Objects.equals(this.sslAuth, service.sslAuth) &&
        Objects.equals(this.subjectsCount, service.subjectsCount) &&
        Objects.equals(this.url, service.url) &&
        Objects.equals(this.endpoints, service.endpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fullServiceCode, serviceCode, timeout, title, sslAuth, subjectsCount, url, endpoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fullServiceCode: ").append(toIndentedString(fullServiceCode)).append("\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    sslAuth: ").append(toIndentedString(sslAuth)).append("\n");
    sb.append("    subjectsCount: ").append(toIndentedString(subjectsCount)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

