/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.govstack.information_mediator.pubsub.management.xroad_admin.client.model.ServiceClientType;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * service client. May be a subsystem, local group, or a global group
 */
@JsonPropertyOrder({
  ServiceClient.JSON_PROPERTY_ID,
  ServiceClient.JSON_PROPERTY_NAME,
  ServiceClient.JSON_PROPERTY_LOCAL_GROUP_CODE,
  ServiceClient.JSON_PROPERTY_SERVICE_CLIENT_TYPE,
  ServiceClient.JSON_PROPERTY_RIGHTS_GIVEN_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServiceClient {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_LOCAL_GROUP_CODE = "local_group_code";
  private String localGroupCode;

  public static final String JSON_PROPERTY_SERVICE_CLIENT_TYPE = "service_client_type";
  private ServiceClientType serviceClientType;

  public static final String JSON_PROPERTY_RIGHTS_GIVEN_AT = "rights_given_at";
  private OffsetDateTime rightsGivenAt;

  public ServiceClient() {
  }

  @JsonCreator
  public ServiceClient(
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_LOCAL_GROUP_CODE) String localGroupCode, 
    @JsonProperty(JSON_PROPERTY_RIGHTS_GIVEN_AT) OffsetDateTime rightsGivenAt
  ) {
    this();
    this.name = name;
    this.localGroupCode = localGroupCode;
    this.rightsGivenAt = rightsGivenAt;
  }

  public ServiceClient id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * subject id - can be a subsystem id &lt;instance_id&gt;:&lt;member_class&gt;:&lt;member_code&gt;:&lt;subsystem&gt; | globalgroup id &lt;instance_id&gt;:&lt;group_code&gt; | localgroup resource id in number format &lt;id&gt;
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


   /**
   * name of the ServiceClient - can be the name of a member or the description of a group
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }




   /**
   * group code in case the object is a local group
   * @return localGroupCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCAL_GROUP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalGroupCode() {
    return localGroupCode;
  }




  public ServiceClient serviceClientType(ServiceClientType serviceClientType) {
    
    this.serviceClientType = serviceClientType;
    return this;
  }

   /**
   * Get serviceClientType
   * @return serviceClientType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_CLIENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServiceClientType getServiceClientType() {
    return serviceClientType;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_CLIENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceClientType(ServiceClientType serviceClientType) {
    this.serviceClientType = serviceClientType;
  }


   /**
   * time when access right were given at. When listing client&#39;s service clients without specifying the service, the time when first service access right was given to this service client for any service. When listing service clients for a specific service, time when service client was added permission to that service.
   * @return rightsGivenAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RIGHTS_GIVEN_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRightsGivenAt() {
    return rightsGivenAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceClient serviceClient = (ServiceClient) o;
    return Objects.equals(this.id, serviceClient.id) &&
        Objects.equals(this.name, serviceClient.name) &&
        Objects.equals(this.localGroupCode, serviceClient.localGroupCode) &&
        Objects.equals(this.serviceClientType, serviceClient.serviceClientType) &&
        Objects.equals(this.rightsGivenAt, serviceClient.rightsGivenAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, localGroupCode, serviceClientType, rightsGivenAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceClient {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localGroupCode: ").append(toIndentedString(localGroupCode)).append("\n");
    sb.append("    serviceClientType: ").append(toIndentedString(serviceClientType)).append("\n");
    sb.append("    rightsGivenAt: ").append(toIndentedString(rightsGivenAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

