/*
 * X-Road Security Server Admin API
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: info@niis.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.govstack.information_mediator.pubsub.management.xroad_admin.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * response that tells if hsm tokens were logged out during the restore process
 */
@JsonPropertyOrder({
  TokensLoggedOut.JSON_PROPERTY_HSM_TOKENS_LOGGED_OUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TokensLoggedOut {
  public static final String JSON_PROPERTY_HSM_TOKENS_LOGGED_OUT = "hsm_tokens_logged_out";
  private Boolean hsmTokensLoggedOut = false;

  public TokensLoggedOut() {
  }

  public TokensLoggedOut hsmTokensLoggedOut(Boolean hsmTokensLoggedOut) {
    
    this.hsmTokensLoggedOut = hsmTokensLoggedOut;
    return this;
  }

   /**
   * whether any hsm tokens were logged out during the restore process
   * @return hsmTokensLoggedOut
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HSM_TOKENS_LOGGED_OUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHsmTokensLoggedOut() {
    return hsmTokensLoggedOut;
  }


  @JsonProperty(JSON_PROPERTY_HSM_TOKENS_LOGGED_OUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHsmTokensLoggedOut(Boolean hsmTokensLoggedOut) {
    this.hsmTokensLoggedOut = hsmTokensLoggedOut;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokensLoggedOut tokensLoggedOut = (TokensLoggedOut) o;
    return Objects.equals(this.hsmTokensLoggedOut, tokensLoggedOut.hsmTokensLoggedOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hsmTokensLoggedOut);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokensLoggedOut {\n");
    sb.append("    hsmTokensLoggedOut: ").append(toIndentedString(hsmTokensLoggedOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

